### ISSUE TITLE
add support for `k8s_namespace` in `env0_environment` resource that deploys a Helm Type Template

### ISSUE THREAD

**Issue by away168** [env0/terraform-provider-env0#879]
**Describe the bug**
`k8s_namespace` is not being saved

**To Reproduce**

Deploy an env0_environment that points to a helm template
Redeploy the same env0_environment
```
  # env0_environment.helm must be replaced
-/+ resource "env0_environment" "helm" {
      - approve_plan_automatically       = false -> null
      ~ deployment_id                    = "7c4e49ad-32f6-4084-89b0-0034bb9cbf13" -> (known after apply)
      ~ id                               = "2cb3786a-05c1-4b57-92cd-815cb11c4ff3" -> (known after apply)
      + k8s_namespace                    = "misc-tests" # forces replacement
        name                             = "argo-requisites-dev"
      ~ output                           = "null" -> (known after apply)
      - ttl                              = "2024-06-21T04:48:00.000Z" -> null
        # (13 unchanged attributes hidden)

      ~ configuration {
            name         = "ENV0_HELM_SET_environment"
          - schema_enum  = [] -> null
            # (6 unchanged attributes hidden)
        }
    }
```

Code used:

main.tf

```hcl
terraform {
  required_providers {
    env0 = {
      source = "env0/env0"
      version = ">= 1.18.12"
    }
  }
}

provider "env0" {
  # Configuration options
}

resource "env0_environment" "helm" {
  project_id  = "9ab305ff-3c4b-4354-9f1d-7a78b87a8d54" # Andrew > Helm Test
  template_id = "504dd2e8-30a1-4b9d-819e-52257f72d688" # helm nginx template

  name      = "argo-requisites-${var.environment}"
  workspace = "argo-requisites-${var.environment}"
  k8s_namespace                    = "misc-tests"
  
  revision                         = "main"
  is_remote_backend                = true
  run_plan_on_pull_requests        = true
  deploy_on_push                   = true
  auto_deploy_on_path_changes_only = true
  prevent_auto_deploy              = true
  auto_deploy_by_custom_glob       = "+((_env0/modules/environment/sre/devops/**)|($${env0_template_dir_path}/**))"
  approve_plan_automatically       = null
  ttl                              = null
  
  configuration {
    type        = "environment"
    name        = "ENV0_HELM_SET_environment"
    value       = var.environment
    is_required = true
    schema_um   = null
  }
}

variable "environment" {
  type    = string
  default = "dev"
}
```

helm template:
points to directory where Chart.yaml is stored `myrepo/helm`

helm code:
myrepo/helm/Chart.yaml
```yaml
apiVersion: v2
version: 1.0.0
name: env0-agent
description: A Helm chart for deploying env0 agent onto Kubernetes
```

myrepo/helm/templates/deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    env0: agent-trigger
spec:
  replicas: 1
  selector:
    matchLabels:
      env0: agent-trigger
  template:
    metadata:
      labels:
        env0: agent-trigger
        {{- if .Values.agentAdditionalLabels -}}
        {{ toYaml .Values.agentAdditionalLabels | nindent 8 }}
        {{- end }}
      annotations:
    spec:
      serviceAccountName: agent-trigger-service-account
      restartPolicy: Always
      volumes:
      containers:
        - name: env0-agent-trigger
          image: nginx:1.19
          imagePullPolicy: Always
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            {{- if .Values.customVolumeMounts -}}
            {{ toYaml .Values.customVolumeMounts | nindent 12 }}
            {{- end }}
          resources:
            limits:
              cpu: 500m
              memory: 1000Mi
```

**Expected behavior**
expect no changes on subsequent deployment.

**Provider Version**
1.18.12

**Screenshots**

Actual environment does not have namespace populated.
![CleanShot 2024-06-20 at 13 58 10](https://github.com/env0/terraform-provider-env0/assets/2107354/87f9dfd0-e397-49aa-9be7-2789dd1c5690)

**Additional context**
